---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zwavejs2mqtt
  namespace: zwavejs2mqtt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zwavejs2mqtt
  namespace: zwavejs2mqtt
  labels:
    app: zwavejs2mqtt
spec:
  replicas: 1
  serviceName: zwavejs2mqtt
  selector:
    matchLabels:
      app: zwavejs2mqtt
  template:
    metadata:
      labels:
        app: zwavejs2mqtt
    spec:
      serviceAccountName: zwavejs2mqtt
      securityContext:
        fsGroup: 1000  # Only works for configmap, hostPath needs chowning on node
      containers:
        - name: zwavejs2mqtt
          image: lansible/zwavejs2mqtt:master
          imagePullPolicy: Always
          securityContext:
            capabilities:
                drop:
                  - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: dash
              containerPort: 8091
          volumeMounts:
            - name: zwavejs2mqtt-config
              mountPath: /config
            - name: zwavejs2mqtt-data
              mountPath: /data
      volumes:
        - name: zwavejs2mqtt-config
          configMap:
            name: zwavejs2mqtt-config
        - name: zwavejs2mqtt-data
          hostPath:
            path: /data/zwavejs2mqtt-data
